#!/bin/bash


## app level 1
pacstrap /mnt linux-hardened linux-firmware mkinitcpio base lvm2 btrfs-progs bubblewrap-suid --noconfirm

## app level 2
pacstrap /mnt sudo debugedit fakeroot pkgconf bison gcc pcre flex wget make gcc curl --noconfirm

## app level 3
pacstrap /mnt uwsm hyprland hyprpicker hyprshot hypridle hyprlock hyprpolkitagent xdg-desktop-portal-hyprland qt5-wayland qt6-wayland wl-clipboard cliphist mailcap brightnessctl --noconfirm

## app level 4
pacstrap /mnt mako waybar wofi mpd mpc --noconfirm

## app level 5
pacstrap /mnt pipewire pipewire-pulse pipewire-jack wireplumber pavucontrol --noconfirm

## app level 6
pacstrap /mnt nautilus nautilus-image-converter sushi --noconfirm

## app level 7
pacstrap /mnt ttf-jetbrains-mono-nerd ttf-droid --noconfirm

## app level 8
pacstrap /mnt kitty kitty-terminfo neovim --noconfirm

## app level 9
pacstrap /mnt gnome-keyring libsecret libpwquality cracklib polkit iptables-nft firewalld apparmor --noconfirm

## app level 10
pacstrap /mnt tang clevis mkinitcpio-nfs-utils luksmeta  --noconfirm

## app level 11
pacstrap /mnt tuned tuned-ppd openssh rsync git btop less --noconfirm

## app level 12
pacstrap /mnt go hugo nginx --noconfirm

## app level 13
pacstrap /mnt intel-ucode --noconfirm


cp -fr mnt/*  /mnt/
cp -fr udev/* /mnt/


genfstab -U /mnt > /mnt/etc/fstab
echo "" >> /mnt/etc/fstab
echo "# /dev/mapper/proc-temp" >> /mnt/etc/fstab
echo "tmpfs     					/tmp        		tmpfs   defaults,rw,nosuid,nodev,noexec,relatime,size=256M" >>  /mnt/etc/fstab

arch-chroot /mnt