#!/bin/bash


## hostname
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc
timedatectl set-ntp true
timedatectl set-timezone Asia/Jakarta
timedatectl status
timedatectl show-timesync --all
systemctl enable systemd-timesyncd.service


## locale
locale-gen 


## administrator
rm /etc/skel/.bash*
useradd -d /var/usr loki
chown -R loki:loki /var/usr
passwd loki
chmod 700 /var/usr/.ssh/
chmod 600 /var/usr/.ssh/authorized_keys
sudo chattr +i .ssh/authorized_keys
usermod -aG wheel loki


## virtualmin
useradd -d /var/games -u 50 -g games games
passwd -l games


## application
mkdir -p /opt/flat 
ln -sf /opt/flat /var/lib/flatpak
pacstrap /mnt flatpak gnome-software --noconfirm


flatpak install --system -y --noninteractive flathub \
    org.mozilla.firefox \
    com.google.Chrome \
    com.visualstudio.code \
    de.wagnermartin.Plattenalbum \
    md.obsidian.Obsidian \
    org.gnome.Evolution \
    org.gnome.Calculator \
    com.github.tchx84.Flatseal \
    org.keepassxc.KeePassXC \
    org.telegram.desktop \
    org.gnome.World.Secrets \
    com.mongodb.Compass \
    io.beekeeperstudio.Studio \
    fr.free.Homebank \
    
sudo echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/50-bubblewrap.conf


## aide hids
pkg-config --libs --cflags glib-2.0
cd /tmp
wget https://github.com/aide/aide/releases/download/v0.19.2/aide-0.19.2.tar.gz 
sudo tar -xf aide-0.19.2.tar.gz
cd aide-0.19.2
sudo ./configure --with-zlib --with-posix-acl --with-xattr --with-curl --with-locale --with-syslog-ident --with-config-file=/etc/aide.conf
sudo make && make install
mkdir -p /var/lib/aide


## boot config
rm -fr /etc/mkinitcpio.conf.d
rm /boot/initramfs-linux-hardened*
mkdir -p /boot/efi /boot/efi/linux /boot/efi/systemd /boot/efi/rescue /boot/efi/boot /boot/kernel
mv /boot/*-ucode.img /boot/vmlinuz-linux-hardened /boot/kernel


## service activation
systemctl enable systemd-timesyncd.service
systemctl enable tangd.socket
systemctl enable apparmor.service
systemctl enable sshd
systemctl enable update.timer 
systemctl enable prometheus.service
systemctl enable prometheus-node-exporter.service
systemctl enable irqbalance
systemctl enable tuned
systemctl enable tuned-ppd.service
systemctl enable nginx
systemctl enable systemd-networkd
systemctl enable systemd-resolved
systemctl enable aide.timer
systemctl enable sddm
systemctl enable --global gcr-ssh-agent.socket
systemctl enable --global hypridle.service
systemctl enable --global hyprpolkitagent
systemctl enable --global waybar
systemctl enable --global pipewire-pulse

## boot command
bootctl --path=/boot install
mkinitcpio -P